-- ALTER SEQUENCE films_id_seq RESTART WITH 7 INCREMENT BY 1 MINVALUE 1;
-- ALTER SEQUENCE genres_id_seq RESTART WITH 13 INCREMENT BY 1 MINVALUE 1;
-- ALTER SEQUENCE persons_id_seq RESTART WITH 25 INCREMENT BY 1 MINVALUE 1;
-- ALTER SEQUENCE play_id_seq RESTART WITH 20 INCREMENT BY 1 MINVALUE 1;
-- ALTER SEQUENCE review_id_seq RESTART WITH 1 INCREMENT BY 1 MINVALUE 1;
-- ALTER SEQUENCE user_id_seq RESTART WITH 1 INCREMENT BY 1 MINVALUE 1;

ALTER SEQUENCE films_id_seq RESTART WITH 7;
ALTER SEQUENCE genres_id_seq RESTART WITH 13;
ALTER SEQUENCE persons_id_seq RESTART WITH 25;
ALTER SEQUENCE play_id_seq RESTART WITH 20;
ALTER SEQUENCE review_id_seq RESTART WITH 1;
ALTER SEQUENCE user_id_seq RESTART WITH 1;